# Site
repository: mohamed-moaz-ibrahim/mohamed-moaz-ibrahim.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohamed Moaz
title: Data Scientist | Machine Learning Engineer
email: mohamed95moaz@gmail.com
website: https://mohamed-moaz-ibrahim.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: mohamed-moaz
github_username: mohamed-moaz-ibrahim

# Additional icon links
additional_links:
  - title: Kaggle Profile
    icon: fab fa-kaggle
    url: https://www.kaggle.com/mohamedmoaz/datasets

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpeg
about_content: | 
  IBM Data Science and Microsoft Azure AI Fundamentals certified professional with over 7 years of experience spanning software development, data science, and machine learning. I am dedicated to building impactful, data-driven solutions that optimize business operations and drive innovation across various industries, including finance, healthcare, and technology.

  My expertise includes <mark>Python</mark>, <mark>Data Analysis</mark>, <mark>Machine Learning</mark>, and <mark>Computer Vision</mark>, with extensive hands-on experience in data preprocessing, feature engineering, and model development. I am proficient in using tools like TensorFlow, Keras, and OpenCV to create scalable and maintainable AI applications, including predictive models and image recognition systems. My projects, such as car price prediction models and license plate recognition systems, demonstrate my ability to turn complex data into actionable insights.

  I am also skilled in data visualization using libraries like Matplotlib and Seaborn, allowing me to communicate insights effectively to stakeholders. As someone who values collaboration, I have successfully led teams and worked alongside professionals from diverse backgrounds, fostering an inclusive environment that leverages cultural differences to enhance creativity and performance. This experience has equipped me to thrive in fast-paced, dynamic settings and deliver solutions that align with strategic goals and industry standards.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Car Price Evaluation Prediction Model
        description: |
          Developed a machine learning model designed to predict the price of used cars based on a range of vehicle features, including mileage, age, engine size, and more. This project involved data preprocessing, feature engineering, and the use of regression algorithms to build a robust predictive model. Extensive hyperparameter tuning was conducted to improve model accuracy, and the final model demonstrated high predictive reliability, providing valuable insights for pricing strategies in automotive sales and auction environments.

      - layout: top-middle
        title: Quran Dataset on Kaggle
        link: https://www.kaggle.com/datasets/mohamedmoaz/numeric-quran
        description: |
          Created a unique dataset on Kaggle that presents the Quran in numeric format, aiming to support researchers, linguists, and machine learning practitioners in analyzing the text. The dataset has been well-received within the Kaggle community, garnering high ratings and significant engagement. It serves as a valuable resource for natural language processing projects and text-based AI models, and it highlights data curation skills and a focus on supporting open-access educational tools.

      - layout: top-middle
        title: License Plate Recognition
        description: |
          Built an optical character recognition (OCR) and object detection model to automate car license plate recognition, utilizing OpenCV and machine learning techniques. This project involved training a model to detect and interpret license plate characters from images, enabling real-time recognition with high accuracy. Techniques included image preprocessing, object detection, and character segmentation, showcasing expertise in computer vision and OCR. The model can be applied in automated toll systems, parking management, and security applications, demonstrating both the technical and practical applications of AI in real-world scenarios.


  - title: Experience
    layout: list
    content:
      - layout: left
        title: Freelancer, Saudi Arabia
        sub_title: Data Scientist-Machine Learning Engineer
        caption: Nov 2023 – Present
        description: |
          - Built regression models for predicting car prices in auctions.
          - Developed a license plate recognition model using OpenCV, OCR, and object detection.
          - Created a high-engagement Quran dataset on Kaggle.

      - layout: left
        title: First Screen, UAE
        sub_title: Full-Stack Developer
        caption: Jun 2023 – Jul 2024
        description: |
          - Enhanced user targeting by 25% with a traffic tool for the marketing team.
          - Implemented 15+ integrations with telecom operators and aggregators across various regions.
          - Developed an automation tool for document backup, reducing the finance team’s workload by 2 hours per day.

      - layout: left
        title: OrchTech, Egypt
        sub_title: Senior Software Engineer
        caption: Jan 2022 – Apr 2023
        description: |
          - Led a team to develop an HR system used across 29 countries.
          - Upgraded a legacy system, improving responsiveness by 300%.
          - Architected a global project for UN’s COP27 Climate Change event.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Arab Academy for Science, Technology & Maritime Transport, Egypt
        sub_title: Post Graduate Diploma in Computer Science
        caption: 2022 - 2023
        description: "Completed an in-depth program in computer science that covered advanced topics such as data science, algorithms, machine learning, and software engineering. Developed a strong foundation in programming, statistical analysis, and data-driven decision-making. Gained practical experience in data processing, predictive modeling, and using cutting-edge tools and techniques to address complex computational problems. The program emphasized analytical problem-solving and teamwork, preparing me for advanced roles in data science and AI."
      - layout: left
        title: Sudan University of Science & Technology, Sudan
        sub_title: Bachelor of Electronics (Computer and Networks) Engineering
        caption: 2011 - 2016
        description: "Earned a Bachelor’s degree focused on electronics and computer network engineering, providing a comprehensive understanding of both hardware and software aspects of technology. The curriculum included extensive training in programming, network design, digital systems, and embedded systems. Gained hands-on experience in lab environments, working on projects that involved system design, troubleshooting, and optimization. This program equipped me with a solid foundation in engineering principles, critical thinking, and technical skills, forming the basis for my career in technology and software development."

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: IBM Data Scientist Professional
        sub_title: IBM, 2024
        description: "Gained hands-on skills in data analysis, machine learning, and data visualization, with a focus on Python and practical applications in data science."

      - layout: left
        title: Microsoft Azure AI Fundamentals
        sub_title: Microsoft, 2024
        description: "Developed foundational knowledge in artificial intelligence and machine learning concepts, along with practical skills for deploying AI solutions on Microsoft Azure."

      - layout: left
        title: TensorFlow Developer Certificate
        sub_title: TensorFlow, 2024
        description: "Mastered building and deploying machine learning models with TensorFlow, covering neural networks, deep learning, and model optimization techniques."

      - layout: left
        title: Scrum Foundation Professional Certificate (SFPC)
        sub_title: Certiprof, 2024
        description: "Learned the core principles of Scrum and agile project management, including collaboration, sprint planning, and iterative development."

      - layout: left
        title: Microsoft Certified Solution Associate, Web Application (MCSA)
        sub_title: Microsoft, 2020
        description: "Acquired skills in developing, deploying, and managing web applications using Microsoft technologies, with a focus on ASP.NET and SQL Server."

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Chess
      - Drones
      - Swimming
      - Farming

      Look at this cool image  
      ![Farming](/modern-resume-theme/images/farming.jpg "Farming")
      
# Footer
footer_show_references: true
# references_title: References available upon request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
